FAQ_DOCUMENTS = [
    {
        "id": "faq_001",
        "question": "What are the store hours?",
        "answer": "Our store is open Monday to Saturday from 9:00 AM to 9:00 PM, and Sunday from 10:00 AM to 8:00 PM. We are closed on major public holidays.",
        "category": "general",
    },
    {
        "id": "faq_002",
        "question": "What is the return policy?",
        "answer": "Items can be returned within 7 days of purchase with the original receipt. Items must be unused, in original packaging, and in the same condition as purchased. Sale items and perishables are non-returnable.",
        "category": "returns",
    },
    {
        "id": "faq_003",
        "question": "What is the exchange policy?",
        "answer": "We offer hassle-free exchanges within 3 days of purchase, no questions asked. The item must be unused and in original packaging. Size or color exchanges are processed immediately if stock is available.",
        "category": "returns",
    },
    {
        "id": "faq_004",
        "question": "What payment methods are accepted?",
        "answer": "We accept Cash, Debit/Credit Cards (Visa, Mastercard), EasyPaisa, JazzCash, and Bank Transfers. Card payments are accepted for orders above Rs.500.",
        "category": "payment",
    },
    {
        "id": "faq_005",
        "question": "Do you offer home delivery?",
        "answer": "Yes! We offer free home delivery within the city for orders above Rs.2,000. Orders below Rs.2,000 have a delivery charge of Rs.150. Delivery takes 1-3 working days.",
        "category": "delivery",
    },
    {
        "id": "faq_006",
        "question": "How does the loyalty points program work?",
        "answer": "Earn 1 loyalty point for every Rs.100 spent. Points accumulate in your account and can be redeemed: 100 points = Rs.10 discount on your next purchase. Points expire after 12 months of account inactivity.",
        "category": "loyalty",
    },
    {
        "id": "faq_007",
        "question": "How do I redeem my loyalty points?",
        "answer": "At checkout, inform the cashier you want to redeem loyalty points. Minimum redemption is 100 points (Rs.10 discount). You can redeem up to 50% of your bill amount using points.",
        "category": "loyalty",
    },
    {
        "id": "faq_008",
        "question": "What is the warranty on electronics?",
        "answer": "All electronics come with a 1-year manufacturer warranty covering manufacturing defects. Physical damage, water damage, and software issues are not covered. Bring your receipt and original packaging for warranty claims.",
        "category": "warranty",
    },
    {
        "id": "faq_009",
        "question": "What is the warranty on non-electronics items?",
        "answer": "Non-electronic items such as clothing, kitchenware, and sports equipment carry a 30-day warranty for manufacturing defects. Items showing signs of misuse or normal wear are not covered.",
        "category": "warranty",
    },
    {
        "id": "faq_010",
        "question": "How do I track my online order?",
        "answer": "After placing an order, you will receive an SMS and email with your order number. Call our customer service at 0800-RETAIL or WhatsApp us to get a real-time status update on your order.",
        "category": "delivery",
    },
    {
        "id": "faq_011",
        "question": "Can I cancel my order?",
        "answer": "Orders can be cancelled within 2 hours of placement for a full refund. After 2 hours, if the order has been dispatched, cancellation is not possible. Contact customer service immediately to request cancellation.",
        "category": "returns",
    },
    {
        "id": "faq_012",
        "question": "How long does refund take?",
        "answer": "Cash refunds are processed immediately at the store. Card refunds take 5-7 working days to reflect in your account. EasyPaisa and JazzCash refunds are processed within 24-48 hours.",
        "category": "returns",
    },
    {
        "id": "faq_013",
        "question": "Do you have a student discount?",
        "answer": "Yes! Students get a 10% discount on books and stationery by showing a valid student ID. This discount is not applicable on sale items or combined with other offers.",
        "category": "discounts",
    },
    {
        "id": "faq_014",
        "question": "Are there any bulk purchase discounts?",
        "answer": "Yes, we offer bulk discounts for orders above Rs.50,000: 5% discount. Above Rs.1,00,000: 10% discount. Contact our sales team at sales@retailstore.pk for bulk orders.",
        "category": "discounts",
    },
    {
        "id": "faq_015",
        "question": "How do I register a complaint?",
        "answer": "You can register a complaint by visiting the store and asking for the Customer Service desk, calling 0800-RETAIL, emailing complaints@retailstore.pk, or through our website. All complaints receive a reference number and are resolved within 48 hours.",
        "category": "complaints",
    },
    {
        "id": "faq_016",
        "question": "What if I received a damaged or wrong product?",
        "answer": "We apologize for the inconvenience! Contact us within 24 hours of delivery with photos of the damaged/wrong item. We will arrange an immediate replacement or full refund at no extra cost to you.",
        "category": "complaints",
    },
    {
        "id": "faq_017",
        "question": "Do you offer gift wrapping?",
        "answer": "Yes, gift wrapping is available for Rs.50 per item. We offer premium gift boxes for Rs.150 per item. You can add a personalized message card for free. Available at the store and for online orders.",
        "category": "general",
    },
    {
        "id": "faq_018",
        "question": "Is there a minimum order amount for online orders?",
        "answer": "There is no minimum order amount. However, for orders below Rs.500, a handling fee of Rs.50 applies. Orders above Rs.2,000 qualify for free delivery.",
        "category": "delivery",
    },
    {
        "id": "faq_019",
        "question": "Do you have installment plans?",
        "answer": "Yes, we offer 0% installment plans for purchases above Rs.10,000 on select bank cards (HBL, MCB, UBL, Meezan Bank). Plans available for 3, 6, and 12 months. Ask at the counter for eligible items.",
        "category": "payment",
    },
    {
        "id": "faq_020",
        "question": "How do I create an account?",
        "answer": "You can register at our store counter with your CNIC and phone number, or online at our website. Membership is free and gives you access to loyalty points, exclusive deals, and order tracking.",
        "category": "account",
    },
    {
        "id": "faq_021",
        "question": "What if I forgot my loyalty card?",
        "answer": "No problem! Your account is linked to your phone number. Simply provide your registered phone number at checkout to access your loyalty points. You do not need the physical card.",
        "category": "loyalty",
    },
    {
        "id": "faq_022",
        "question": "Do you price match with competitors?",
        "answer": "Yes, we offer price matching! If you find the same product at a lower price at a verified competitor, show us proof and we will match the price. Price matching is valid on identical products only, excluding clearance items.",
        "category": "discounts",
    },
    {
        "id": "faq_023",
        "question": "Can I reserve a product?",
        "answer": "Yes, products can be reserved for up to 48 hours by paying a 20% advance. If the reservation is not confirmed within 48 hours, the advance is refunded and the item is released.",
        "category": "general",
    },
    {
        "id": "faq_024",
        "question": "Do you sell online?",
        "answer": "Yes! Shop online at our website or WhatsApp your order to 0300-RETAIL. We deliver across Pakistan. Karachi, Lahore, and Islamabad orders are delivered within 1-2 days; other cities within 3-5 days.",
        "category": "delivery",
    },
    {
        "id": "faq_025",
        "question": "What is your privacy policy regarding customer data?",
        "answer": "We take your privacy seriously. Your personal data (name, phone, address) is used only for order processing and loyalty program management. We never share your data with third parties. You can request data deletion by contacting us.",
        "category": "account",
    },
    {
        "id": "faq_026",
        "question": "Are there seasonal sales or promotions?",
        "answer": "Yes! We run major sales during Eid (Eid-ul-Fitr and Eid-ul-Adha), Independence Day (14 August), and the Winter Sale (December-January). Subscribe to our SMS alerts to stay informed about upcoming promotions.",
        "category": "discounts",
    },
    {
        "id": "faq_027",
        "question": "How do I update my contact information?",
        "answer": "Visit the store with your CNIC to update your registered phone number or address. Email changes can be done via our website after logging in. Changes take effect immediately.",
        "category": "account",
    },
    {
        "id": "faq_028",
        "question": "Do you accept corporate orders?",
        "answer": "Yes, we handle corporate bulk orders with special pricing and credit terms for registered businesses. Contact our B2B team at corporate@retailstore.pk with your NTN number and requirements.",
        "category": "general",
    },
]
